window.LECTURA = {
  "book": { "title": "El calcetín de Agustín", "author": "Mauricio Paredes", "illustrator": "Verónica Laymuns", "icon": "🧦" },
  "perRound": 10,
  "phrases": {
    "start": "Escucha la pregunta y toca la respuesta correcta.",
    "ok": ["¡Muy bien!", "¡Excelente!", "¡Lo sabías!", "¡Bravo!"],
    "bad": "¡Casi! La respuesta correcta es:",
    "end": "¡Terminaste! ¡Eres una gran lectora!"
  },
  "questions": [
    { "q": "¿Qué animal es Agustín?",
      "a": [["🦌", "Un pudú"], ["🐰", "Un conejo"], ["🐶", "Un perro"]],
      "why": "Agustín es un pudú, el ciervo más pequeño del mundo." },
    { "q": "Al comienzo del cuento, ¿qué fiesta es mañana?",
      "a": [["🎄", "Navidad"], ["🎂", "Su cumpleaños"], ["🎆", "Año Nuevo"]],
      "why": "Mañana es Navidad, y Agustín salta de felicidad." },
    { "q": "¿Qué quiere hacer Agustín?",
      "a": [["⛸️", "Patinar en hielo"], ["🏊", "Nadar en el mar"], ["🚲", "Andar en bicicleta"]],
      "why": "Agustín quiere patinar en hielo, como lo vio en la tele." },
    { "q": "¿Por qué no hay nieve en diciembre donde vive Agustín?",
      "a": [["☀️", "Porque es verano y hace calor"], ["🌙", "Porque es de noche"], ["🌧️", "Porque llueve mucho"]],
      "why": "Agustín vive en el sur del mundo. Allí, en diciembre es verano y hace mucho calor." },
    { "q": "¿Qué le faltaba a Agustín para patinar?",
      "a": [["⛸️", "Patines y hielo"], ["🧢", "Un gorro"], ["🧤", "Unos guantes"]],
      "why": "Agustín no tenía patines, ni tampoco hielo." },
    { "q": "¿Qué estaban armando la mamá y el papá?",
      "a": [["🎄", "El árbol de Navidad"], ["🏠", "Una casa de juguete"], ["🪁", "Un volantín"]],
      "why": "La mamá y el papá estaban armando el árbol de Navidad." },
    { "q": "¿Qué dijo Agustín para no ayudar con el árbol?",
      "a": [["🛁", "Que se tenía que bañar"], ["😴", "Que tenía sueño"], ["🍽️", "Que tenía hambre"]],
      "why": "Dijo que se tenía que bañar, pero no fue a bañarse." },
    { "q": "¿Dónde estaba colgado el calcetín?",
      "a": [["🔥", "Sobre la chimenea"], ["🎄", "En el árbol"], ["🪟", "En la ventana"]],
      "why": "El calcetín estaba colgado sobre la chimenea." },
    { "q": "¿Para qué quería Agustín el calcetín?",
      "a": [["⛸️", "Para usarlo como patín"], ["🧢", "Para ponérselo de gorro"], ["🍬", "Para guardar dulces"]],
      "why": "Agustín pensó: el calcetín será mi patín y el suelo será mi hielo." },
    { "q": "¿Agustín pidió permiso para sacar el calcetín?",
      "a": [["🙊", "No, lo sacó sin que sus papás se dieran cuenta"], ["🙋", "Sí, le pidió permiso a su mamá"], ["🙋‍♂️", "Sí, le pidió permiso a su papá"]],
      "why": "Agustín sacó el calcetín de un tirón, sin que sus papás se dieran cuenta." },
    { "q": "¿Qué pasó cuando Agustín patinó con el calcetín?",
      "a": [["📚", "Resbaló, chocó y se cayeron muchos libros"], ["🏆", "Ganó una carrera"], ["😴", "Se quedó dormido"]],
      "why": "Agustín patinó, resbaló, se revolcó y chocó. ¡Se cayeron muchos libros!" },
    { "q": "Con tanta acción, ¿cómo quedó Agustín?",
      "a": [["💦", "Transpirado"], ["🥶", "Congelado"], ["😴", "Dormido"]],
      "why": "Con tanto patinar, Agustín quedó cubierto de transpiración." },
    { "q": "¿Qué le pasó al calcetín?",
      "a": [["🕳️", "Se le hizo un agujero"], ["🔵", "Se puso azul"], ["🌳", "Se perdió en el jardín"]],
      "why": "De tanto patinar, al calcetín se le hizo un agujero." },
    { "q": "Cuando el papá preguntó por el calcetín, ¿qué hizo Agustín?",
      "a": [["🤥", "Dijo una mentira"], ["🗣️", "Dijo la verdad"], ["🙈", "Se escondió debajo de la cama"]],
      "why": "Agustín le mintió al papá. Dijo que no había usado el calcetín." },
    { "q": "¿Para qué era el calcetín colgado en la chimenea?",
      "a": [["🎁", "Para poner el regalo de Navidad"], ["🥶", "Para abrigarse del frío"], ["🧸", "Para vestir a un peluche"]],
      "why": "En ese calcetín iban a poner el regalo de Navidad de Agustín." },
    { "q": "¿Cómo olían el calcetín y la pata de Agustín?",
      "a": [["🤢", "Mal, ¡apestaban!"], ["🌸", "A flores"], ["🍫", "A chocolate"]],
      "why": "¡Guácatela! El calcetín y la pata de Agustín apestaban." },
    { "q": "¿Cómo se sintieron la mamá y el papá?",
      "a": [["😠", "Enojados"], ["😄", "Muy felices"], ["😱", "Asustados"]],
      "why": "La mamá y el papá estaban enojados. No les pareció divertido." },
    { "q": "¿Qué hizo Agustín cuando entendió que se había portado mal?",
      "a": [["😢", "Se tiró al suelo y lloró"], ["😂", "Se rió mucho"], ["⚽", "Se fue a jugar a la pelota"]],
      "why": "Agustín se tiró al suelo y lloró. Estaba triste porque se portó mal." },
    { "q": "Según el cuento, ¿cada cuánto hay que bañarse?",
      "a": [["🛁", "Todos los días"], ["📅", "Una vez a la semana"], ["🎄", "Solo en Navidad"]],
      "why": "Bañarse no es un castigo. ¡Hay que hacerlo todos los días!" },
    { "q": "¿Qué hizo el papá con el calcetín?",
      "a": [["🧺", "Lo metió en la lavadora"], ["🗑️", "Lo botó a la basura"], ["🎄", "Lo colgó en el árbol"]],
      "why": "Mientras Agustín se bañaba, el papá metió el calcetín en la lavadora." },
    { "q": "¿Qué hizo Agustín para arreglar el desorden?",
      "a": [["🧹", "Ordenó su pieza, la salita y el comedor"], ["😴", "Se fue a dormir"], ["🛍️", "Compró otro calcetín"]],
      "why": "Agustín ordenó todo el desorden. ¡Todo quedó de lo mejor!" },
    { "q": "¿Qué le dijeron sus papás a Agustín?",
      "a": [["❤️", "Aunque te portes mal, te queremos igual"], ["💔", "Ya no te queremos"], ["🚫", "Este año no hay regalos"]],
      "why": "Sus papás le dijeron: aunque te portes mal, te queremos igual." },
    { "q": "¿Qué error cometió el papá?",
      "a": [["👕", "Lavó el calcetín con toda la ropa"], ["💥", "Rompió la lavadora"], ["🔍", "Perdió el calcetín"]],
      "why": "El papá mezcló el calcetín con toda la ropa en la lavadora." },
    { "q": "¿Cómo quedó el calcetín después de lavarlo?",
      "a": [["🌈", "De muchos colores"], ["⚫", "Todo negro"], ["🫥", "Invisible"]],
      "why": "¡El calcetín quedó multicolor! Y a todos les encantó." },
    { "q": "¿Qué regalo recibió Agustín en Navidad?",
      "a": [["🧦", "Calcetines"], ["⛸️", "Patines"], ["⚽", "Una pelota"]],
      "why": "Agustín recibió calcetines. ¡Adivinaron su pensamiento!" },
    { "q": "¿Cómo se sintió Agustín con su regalo?",
      "a": [["🥳", "Feliz, saltó y bailó"], ["😢", "Triste"], ["😠", "Enojado"]],
      "why": "Agustín saltó y bailó de contento con sus calcetines." },
    { "q": "¿Qué pasó primero en el cuento?",
      "a": [["🧦", "Agustín sacó el calcetín de la chimenea"], ["🎁", "Agustín abrió su regalo"], ["🧺", "El papá lavó el calcetín"]],
      "why": "Primero Agustín sacó el calcetín. Después vino todo lo demás." },
    { "q": "¿Qué pasó al final del cuento?",
      "a": [["🎁", "Agustín recibió calcetines de regalo"], ["⛸️", "Agustín patinó en el hielo"], ["🎄", "Agustín ayudó a armar el árbol"]],
      "why": "Al final, en Navidad, Agustín recibió calcetines de regalo." },
    { "q": "¿Quién escribió este libro?",
      "a": [["✍️", "Mauricio Paredes"], ["🎨", "Verónica Laymuns"], ["🦌", "El pudú Agustín"]],
      "why": "El autor del libro es Mauricio Paredes." },
    { "q": "¿Quién hizo los dibujos del libro?",
      "a": [["🎨", "Verónica Laymuns"], ["✍️", "Mauricio Paredes"], ["👩", "La mamá de Agustín"]],
      "why": "La ilustradora del libro es Verónica Laymuns." },
    { "q": "¿Qué nos enseña este cuento?",
      "a": [["💡", "Decir la verdad y arreglar lo que hicimos mal"], ["🤥", "Que mentir está bien"], ["🚿", "Que no hay que bañarse"]],
      "why": "Cuando nos portamos mal, podemos decir la verdad y arreglarlo. ¡Y nos siguen queriendo!" }
  ]
};
